[numpy random 함수]

- np.random.seed : seed를 통한 난수 생성
- np.random.randint : 정수 난수 1개 생성
- np.random.rand : 0부터 1사이의 균일분포에서 난수 매트릭스 배열 생성
- np.random.randn : 가우시안 표준 정규분포에서 난수 매트릭스 배열 생성
- np.random.shuffle : 기존의 데이터의 순서 바꾸기
- np.random.choice : 기존 데이터에서 sampling


In [26]:
# Python random
import random
print(random.random(),'\n') #0.0~1.0 사이 랜덤한 숫자
print(random.randint(1,10),'\n')# 1~10 사이의 정수 중에서 난수 값 리턴
print(random.uniform(10,20),'\n')#min,max 사이의 float 리턴
print(random.randrange(10),'\n')#지정 범위 int 리턴
print(random.choice([1,2,3,4,5]),'\n')#리스트 내부에 있는 요소를 랜덤하게 선택
li = [1,2,3,4,5]
print(random.sample(li,3), '\n') #리스트 요소를 중복이 안되게 리턴
random.shuffle(li) #리스트 요소를 다시 섞어서 리턴
print(li) #섞인 리스트

0.9387290120768739 

8 

10.801320542208114 

2 

5 

[3, 1, 4] 

[1, 2, 4, 3, 5]


In [11]:
import numpy as np
r = np.random.rand(6)
r

array([0.28896275, 0.75554676, 0.55512055, 0.15191074, 0.58365717,
       0.16059633])

In [18]:
import numpy as np
r = np.random.rand(10000)  # 0 ~ 1 사이의 균일 분포
print('='*50)
print(r.mean())
print(r.std())

0.5040125449296429
0.28661929753421017


In [20]:
# 표준 정규분포
r = np.random.randn(10000)
print('='*50)
print(r.mean())
print(r.std())

-0.0015346992234481895
0.9919054145792584


In [16]:
# 1.0 <= x < 2.0 사이 float 값 10개 리턴
# np.random.random_sample() 함수와 다르게 최소, 최대값을 지정해줄 수 있다.
np.random.uniform(1.0,2.0,10)  

array([1.10142321, 1.92852834, 1.74291325, 1.81990309, 1.1163583 ,
       1.53226573, 1.58337249, 1.78728613, 1.43620566, 1.46937972])

In [17]:
np.random.uniform(1.0,2.0,10)

array([1.83255967, 1.81325712, 1.99246547, 1.06798157, 1.22210524,
       1.37122292, 1.55162337, 1.78302394, 1.73149918, 1.57317149])

In [4]:
np.random.uniform(0,1,(2,3))

array([[0.29603817, 0.43570971, 0.90481468],
       [0.44212263, 0.85972087, 0.27091756]])

In [6]:
#0~1사이의 난수 실수값으로 행렬 생성
#uniform 함수의 최소값, 최대값을 0,1fh wlwjdgks rjtrhk rkxdma
np.random.random_sample((2,3))

array([[0.49354063, 0.67627258, 0.69423115],
       [0.24341772, 0.24654702, 0.9895303 ]])

In [23]:
# 배열을 df로 변환
# coloumns 8개에 대한 이름 columns = ['id','gender','age','region','product','price','qty','time']
import pandas as pd
ar = np.random.rand(4,8)
print(ar)
ard = pd.DataFrame(ar,
                   columns = ['id','gender','age','region','product','price','qty','time']
)
ard

[[0.73742514 0.06965909 0.98032622 0.9157684  0.33961902 0.14938228
  0.20190492 0.43507689]
 [0.44631255 0.37374117 0.70718874 0.17591599 0.97320134 0.47295458
  0.38610321 0.350076  ]
 [0.26353715 0.03203028 0.69118474 0.25162501 0.94830551 0.90787737
  0.48279423 0.14657475]
 [0.15301364 0.54089372 0.77123943 0.07916045 0.93646836 0.69937534
  0.58853212 0.15314599]]


id    gender       age    region   product     price       qty  \
0  0.737425  0.069659  0.980326  0.915768  0.339619  0.149382  0.201905   
1  0.446313  0.373741  0.707189  0.175916  0.973201  0.472955  0.386103   
2  0.263537  0.032030  0.691185  0.251625  0.948306  0.907877  0.482794   
3  0.153014  0.540894  0.771239  0.079160  0.936468  0.699375  0.588532   

       time  
0  0.435077  
1  0.350076  
2  0.146575  
3  0.153146

In [24]:
# Q. id, gender, age 컬럼에 대하여 의미있는 값으로 변환하여 3개의 컬럼으로 구성된 df3를 출력하세요.

In [55]:
ard.id = np.random.randint(100000,999999,4)
ard.gender = np.random.choice(['male','female'],4)
ard.age = np.random.randint(0,100,4)
ard


id  gender  age    region   product     price       qty      time
0  908571  female   88  0.915768  0.339619  0.149382  0.201905  0.435077
1  960749  female   31  0.175916  0.973201  0.472955  0.386103  0.350076
2  692338    male   50  0.251625  0.948306  0.907877  0.482794  0.146575
3  840484  female   33  0.079160  0.936468  0.699375  0.588532  0.153146

In [65]:

ard.id =np.random.randint(1000,9999,4)
ard.gender = np.random.randint(0,1,4)
ard.age = np.random.randint(1,100,4)
df3 = ard[['id','gender','age']]
df3

id  gender  age
0  3378       0   34
1  9448       0   89
2  1196       0   32
3  1039       0   50

In [74]:
# 배열에서 정렬한 후 50%에 해당하는 원소만 출력
large_ar = np.random.randn(1000)
large_ar.sort()

In [75]:
large_ar[int(0.5*len(large_ar))]

-0.11046883877018035

In [76]:
# 배열 집합 연산
names = np.array(['Bob','Joe','Will','Joe','Joe'])
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [77]:
names = np.array(['Bob','Joe','Will','Joe','Joe'])
sorted(set(names))

['Bob', 'Joe', 'Will']

In [78]:
# 첫번째 배열의 원소가 두번째 배열의 원소를 포함하는지 알려주는 불리언 배열을 반환
values = np.array([6,0,0,3,2,5,6])
np.in1d(values, [2,3,6]) #인원드


array([ True, False, False,  True,  True, False,  True])

In [79]:
# 배열 데이터의 입출력
ar = np.arange(10)
np.save('some_ar',ar)

In [82]:
np.load('some_ar.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [83]:
# np.savez : 여러 개의 배열을 압축된 형식으로 저장
np.savez('ar_archive.npz',a = ar, b=ar)

In [85]:
arch = np.load('ar_archive.npz')
arch['b']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [89]:
a = np.arange(1,10)
print(a,'\n')
np.argsort(a)

[1 2 3 4 5 6 7 8 9] 



array([0, 1, 2, 3, 4, 5, 6, 7, 8], dtype=int64)

In [102]:
#인덱스 배열을 역순으로 출력
np.argsort(a)[::-1]

array([8, 7, 6, 5, 4, 3, 2, 1, 0], dtype=int64)

In [98]:
np.argsort(a)[::2]

array([0, 2, 4, 6, 8], dtype=int64)

### 도전과제(7/6)
- np.arange(336).reshape(6,7,8)에서 100번째 요소의 인덱스를 구하세요.
- np.arange(4)을 이용해서 아래와 같이 출력하세요.

In [ ]:
array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [192]:
#np.arange(336).reshape(6,7,8)에서 100번째 요소의 인덱스를 구하세요.
ar = np.arange(336).reshape(6,7,8)

ar.reshape(-1)[100]
np.where(ar == 100)

(array([1], dtype=int64), array([5], dtype=int64), array([4], dtype=int64))

In [225]:
#np.arange(4)을 이용해서 아래와 같이 출력하세요.
arr = np.eye(5,k=-1)
ar = np.arange(1,6)
arr*ar

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [0., 0., 3., 0., 0.],
       [0., 0., 0., 4., 0.]])

In [ ]:
# Q 0~10 정수 (5,5) 행렬의 역행렬을 구한 후, 두 행렬 간의 행렬 곱을 구하세요.

In [123]:
ab= np.random.randint(0,11,size=(5,5))
ab2 = np.linalg.inv(ab)
print(ab2, '\n')
ap = np.dot(ab,ab2)
print(ap)

[[-0.18879498  0.01090513  0.28912214 -0.0881952  -0.05684297]
 [ 0.05534351  0.00763359 -0.1851145   0.15076336  0.04770992]
 [-0.00845147  0.01853871 -0.02099237 -0.06243184  0.11586696]
 [ 0.1778217   0.13413304 -0.24379771  0.01519902 -0.09916848]
 [ 0.04423391 -0.05670665  0.13406489 -0.00388495 -0.04191658]] 

[[ 1.00000000e+00 -2.08166817e-17  0.00000000e+00 -2.64545330e-17
  -1.38777878e-17]
 [ 1.38777878e-17  1.00000000e+00 -2.22044605e-16 -6.28837260e-17
  -1.24900090e-16]
 [ 5.55111512e-17 -5.55111512e-17  1.00000000e+00 -5.89805982e-17
   0.00000000e+00]
 [ 6.93889390e-17  6.24500451e-17 -2.22044605e-16  1.00000000e+00
  -1.38777878e-17]
 [ 5.55111512e-17  0.00000000e+00 -2.22044605e-16 -5.72458747e-17
   1.00000000e+00]]


### 과제(7/6)


### 아래 가이드에 따라서 고객별 연간 구매데이터를 생성하고 아래사항을 수행하세요(관측치 1000개)

#### Q1. 고객 속성(id, 성별, 연령, 거주지역) 데이터와 거래 데이터를 통합한 데이터 프레임 df를 생성하세요.

거래 번호
- id : 1 ~ 1000번 일련번호 - 개시 후 1천 건의 거래가 있었고 걍 거기에 넘버링한 거라고 이해해보자

고객별 속성 데이터
- cusno : 고객번호 1000개 랜덤
- gender : 0,1 정수 난수 생성
- age : 0 ~ 80사이 정수 난수 생성
- region : 1 ~ 10 사이 정수 난수 생성

거래 데이터
- product_20 : 고가제품(10), 중가제품(20), 저가제품(30)로 구분제품코드 10,20,30
- product_21 : 고가제품(10), 중가제품(20), 저가제품(30)로 구분제품코드 10,20,30
- price_20 : 1000 ~ 50000 사이 실수 난수 생성
- price_21 : 1000 ~ 50000 사이 실수 난수 생성
- quantity_20 : 1 ~ 100 사이 정수 난수 생성
- quantity_21 : 1 ~ 100 사이 정수 난수 생성
- amount_20 : price_20 * quantity_20
- amount_21 : price_21 * quantity_21
- sales : 20년 대비 21년구매금액이 증가면 1, 감소면 0

#### Q2. df를 수정하여 5가지 이상의 인사이트를 포함한 데이터 셋으로 변환하세요

#### Q3. df 를 탐색적 분석을 통하여 인사이트를 도출하세요.


In [9]:
import pandas as pd
import numpy as np
import random
np.random.seed(0)
ar = np.random.rand(1000,13)

ard = pd.DataFrame(ar, index = range(1,1001), 
                   columns = ["cusno", "gender",'age','region','product_20','product_21','price_20','price_21','quantity_20','quantity_21','amount_20','amount_21','sales'])
ard.index.name = "ID"
ard.head()

cusno    gender       age    region  product_20  product_21  price_20  \
ID                                                                             
1   0.548814  0.715189  0.602763  0.544883    0.423655    0.645894  0.437587   
2   0.925597  0.071036  0.087129  0.020218    0.832620    0.778157  0.870012   
3   0.143353  0.944669  0.521848  0.414662    0.264556    0.774234  0.456150   
4   0.681820  0.359508  0.437032  0.697631    0.060225    0.666767  0.670638   
5   0.988374  0.102045  0.208877  0.161310    0.653108    0.253292  0.466311   

    price_21  quantity_20  quantity_21  amount_20  amount_21     sales  
ID                                                                      
1   0.891773     0.963663     0.383442   0.791725   0.528895  0.568045  
2   0.978618     0.799159     0.461479   0.780529   0.118274  0.639921  
3   0.568434     0.018790     0.617635   0.612096   0.616934  0.943748  
4   0.210383     0.128926     0.315428   0.363711   0.570197  0.438602  
5   0.244426     0.158970     0.110375   0.656330   0.138183  0.196582

In [10]:
li = []
for i in range(1000, 2001):
    li.append(i)
ard.cusno = random.sample(li,1000)
ard.gender = np.random.randint(0,2,1000)
ard.age = np.random.randint(0,81,1000)
ard.region = np.random.randint(1,11,1000)

In [11]:
ard.price_20 = np.random.uniform(1000,5001,1000)
ard.price_21 = np.random.uniform(1000,5001,1000)
ard.quantity_20 = np.random.randint(1,101,1000)
ard.quantity_21 = np.random.randint(1,101,1000)

ard["amount_20"] = ard.price_20*ard.quantity_20
ard["amount_21"] = ard.price_21*ard.quantity_21

In [12]:
ard["sales"] = ard['amount_21']>ard['amount_20']
ard['sales'].replace({True : 1, False : 0}, inplace = True)

In [13]:
count, bin_dividers = np.histogram(ard.price_20, bins = 3)
bin_names = ['30','20','10']
ard.product_20 = pd.cut(x = ard.price_20,
                          bins=bin_dividers,
                          labels = bin_names,
                          include_lowest = True)

bin_dividers = np.linspace(sal.price_20.min(), sal.price_20.max(), 4)
bin_names = ['10','20','30']
sal['product_20'] = pd.cut(x=sal.price_20,  # 데이터 배열
                           bins=bin_dividers,  # 경계값 리스트
                           labels=bin_names,  # bin 이름
                           include_lowest=True)  # 첫 경계값 포함 여부
bin_dividers = np.linspace(sal.price_21.min(), sal.price_21.max(), 4)
bin_names = ['10','20','30']
sal['product_21'] = pd.cut(x=sal.price_21,  # 데이터 배열
                           bins=bin_dividers,  # 경계값 리스트
                           labels=bin_names,  # bin 이름
                           include_lowest=True)  # 첫 경계값 포함 여부
sal


In [14]:
count, bin_dividers = np.histogram(ard.price_21, bins = 3)
bin_names = ['30','20','10']
ard.product_21 = pd.cut(x = ard.price_21,
                          bins=bin_dividers,
                          labels = bin_names,
                          include_lowest = True)

In [18]:
ard.head()

cusno  gender  age  region product_20 product_21     price_20  \
ID                                                                  
1    1316       1   41       3         10         20  3755.464364   
2    1266       0   12       2         30         30  1204.099889   
3    1713       0   38       5         30         10  1249.915198   
4    1372       0   18      10         30         20  1776.698013   
5    1166       0   41       6         20         30  3350.212178   

       price_21  quantity_20  quantity_21      amount_20      amount_21  sales  
ID                                                                              
1   3011.357074          100           36  375546.436437  108408.854650      0  
2   2322.295750           38           65   45755.795799  150949.223763      1  
3   3701.383627           94           45  117492.028641  166562.263198      1  
4   2391.231390           26           94   46194.148334  224775.750665      1  
5   1172.358685           38           45  127308.062747   52756.140836      0

In [19]:
insite_df = ard.copy()

In [20]:
#1
count, bin_dividers = np.histogram(insite_df.amount_20, bins = 3)
bin_names = ['Bronz','Silver','Gold']
insite_df.product_20 = pd.cut(x = insite_df.amount_20,
                          bins=bin_dividers,
                          labels = bin_names,
                          include_lowest = True)

In [21]:
count, bin_dividers = np.histogram(insite_df.amount_21, bins = 3)
bin_names = ['Bronz','Silver','Gold']
insite_df.product_21 = pd.cut(x = insite_df.amount_21,
                          bins=bin_dividers,
                          labels = bin_names,
                          include_lowest = True)

In [22]:
#2
insite_df.rename(columns = {"product_20" : "Grade_20","product_21" : "Grade_21","quantity_20":"visit_20","quantity_21":"visit_21"}, inplace = True)

In [23]:
insite_df.head()

cusno  gender  age  region Grade_20 Grade_21     price_20     price_21  \
ID                                                                           
1    1316       1   41       3     Gold    Bronz  3755.464364  3011.357074   
2    1266       0   12       2    Bronz    Bronz  1204.099889  2322.295750   
3    1713       0   38       5    Bronz   Silver  1249.915198  3701.383627   
4    1372       0   18      10    Bronz   Silver  1776.698013  2391.231390   
5    1166       0   41       6    Bronz    Bronz  3350.212178  1172.358685   

    visit_20  visit_21      amount_20      amount_21  sales  
ID                                                           
1        100        36  375546.436437  108408.854650      0  
2         38        65   45755.795799  150949.223763      1  
3         94        45  117492.028641  166562.263198      1  
4         26        94   46194.148334  224775.750665      1  
5         38        45  127308.062747   52756.140836      0

In [24]:
# 여성(1)이면서 구매금액(sales)이 감소한 id
wd = insite_df[(insite_df["gender"] == 1)&(insite_df["sales"] == 0)]
len(wd)/len(insite_df) #전체 고객 중, 여성이면서 구매금액이 감소한 id

0.242

In [25]:
# 남성(0)이면서 구매금액이 감소한 id
md = insite_df[(insite_df["gender"] == 0)&(insite_df['sales'] == 0)]
md
len(md)/len(insite_df)

0.25

In [26]:
#3
#여성과 남성의 구매금액 감소 비중이 의미있게 차이나지 않는다.
#하지만 전체 고객의 총구매금액 감소 고객의 비중이 49% 정도이다.
cd = insite_df[insite_df['sales'] == 0]
len(cd)/len(insite_df)


0.492

In [27]:
GD = insite_df.groupby(['Grade_20', 'Grade_21'])
list(GD)

[(('Bronz', 'Bronz'),
       cusno  gender  age  region Grade_20 Grade_21     price_20     price_21  \
  ID                                                                            
  2     1266       0   12       2    Bronz    Bronz  1204.099889  2322.295750   
  5     1166       0   41       6    Bronz    Bronz  3350.212178  1172.358685   
  6     1018       1   27       5    Bronz    Bronz  2902.246135  2236.681834   
  9     1277       1   10       6    Bronz    Bronz  1158.197047  4190.868383   
  11    1710       0   26       4    Bronz    Bronz  1977.751011  2880.398163   
  ..     ...     ...  ...     ...      ...      ...          ...          ...   
  985   1626       0    4       9    Bronz    Bronz  3933.561390  1950.771233   
  987   1648       1   53       2    Bronz    Bronz  1868.078878  4578.749417   
  989   1908       1   27       2    Bronz    Bronz  1645.477861  2426.270467   
  995   1446       0   15      10    Bronz    Bronz  1349.553026  2035.135039   
  998 

In [28]:
#4 전체 고객 전년도 등급 비교
for key, group in GD:
    print('* key :', key)
    print('* number :', len(group))
    print(group.head(),'\n')

* key : ('Bronz', 'Bronz')
* number : 377
    cusno  gender  age  region Grade_20 Grade_21     price_20     price_21  \
ID                                                                           
2    1266       0   12       2    Bronz    Bronz  1204.099889  2322.295750   
5    1166       0   41       6    Bronz    Bronz  3350.212178  1172.358685   
6    1018       1   27       5    Bronz    Bronz  2902.246135  2236.681834   
9    1277       1   10       6    Bronz    Bronz  1158.197047  4190.868383   
11   1710       0   26       4    Bronz    Bronz  1977.751011  2880.398163   

    visit_20  visit_21      amount_20      amount_21  sales  
ID                                                           
2         38        65   45755.795799  150949.223763      1  
5         38        45  127308.062747   52756.140836      0  
6         47        17  136405.568343   38023.591186      0  
9         91        34  105395.931300  142489.525008      1  
11        39        22   77132.289422  

In [29]:
GD['Grade_20'].value_counts()

Grade_20  Grade_21        
Bronz     Bronz     Bronz     377
                    Silver      0
                    Gold        0
          Silver    Bronz     194
                    Silver      0
                    Gold        0
          Gold      Bronz      68
                    Silver      0
                    Gold        0
Silver    Bronz     Silver    176
                    Bronz       0
                    Gold        0
          Silver    Silver     75
                    Bronz       0
                    Gold        0
          Gold      Silver     28
                    Bronz       0
                    Gold        0
Gold      Bronz     Gold       54
                    Bronz       0
                    Silver      0
          Silver    Gold       20
                    Bronz       0
                    Silver      0
          Gold      Gold        8
                    Bronz       0
                    Silver      0
Name: Grade_20, dtype: int64

In [30]:
# 5
# 위 자료에서 볼 수 있듯이 전년도에 비해 브론즈 등급의 변화가 없는 고객이 전체의 36.2%정도이다.
# 브론즈 등급이 변화가 없거나 등급이 떨어진 고객을 'Question mark = ?'으로 정하겠다.
# 등급이 오른 고객은 'Star', 등급이 같은 고객은 'Cash_Cow'

In [31]:
def bcg(x):
    if (x["Grade_20"] == "Bronz")&(x["Grade_21"] == "Bronz"):
        return "?"
    elif (x["Grade_20"] == "Silver")&(x["Grade_21"] == "Bronz"):
        return "?"
    elif (x["Grade_20"] == "Gold")&(x["Grade_21"] == "Bronz"):
        return "?"
    elif (x["Grade_20"] == "Gold")&(x["Grade_21"] == "Siver"):
        return "?"
    elif (x["Grade_20"] == "Gold")&(x["Grade_21"] == "Gold"):
        return "Cash_Cow"
    elif (x["Grade_20"] == "Silver")&(x["Grade_21"] == "Silver"):
        return "Cash_Cow"
    else:
        return "Star"
    
    
insite_df['BCG'] = insite_df.apply(lambda x: bcg(x), axis=1)
insite_df.head()

cusno  gender  age  region Grade_20 Grade_21     price_20     price_21  \
ID                                                                           
1    1316       1   41       3     Gold    Bronz  3755.464364  3011.357074   
2    1266       0   12       2    Bronz    Bronz  1204.099889  2322.295750   
3    1713       0   38       5    Bronz   Silver  1249.915198  3701.383627   
4    1372       0   18      10    Bronz   Silver  1776.698013  2391.231390   
5    1166       0   41       6    Bronz    Bronz  3350.212178  1172.358685   

    visit_20  visit_21      amount_20      amount_21  sales   BCG  
ID                                                                 
1        100        36  375546.436437  108408.854650      0     ?  
2         38        65   45755.795799  150949.223763      1     ?  
3         94        45  117492.028641  166562.263198      1  Star  
4         26        94   46194.148334  224775.750665      1  Star  
5         38        45  127308.062747   52756.140836      0     ?

In [32]:
insite_df['BCG'].value_counts()

?           607
Star        310
Cash_Cow     83
Name: BCG, dtype: int64

In [33]:
# 위 BCG 컬럼을 적용하여 
# 제품을 구매하지만 등급이 떨어지거나 제품 구매가 더딘 고객에겐 "?"마크를 줘서 이벤트를 열어 구매를 늘리면 혜택을 주는 마케팅을 사용하거나 반대급부인 아무런 관심을 주지 않는 마케팅을 쓸 수도 있다.
# 이와 반대되는 고객들에겐 그에 맞는 맞춤형 마케팅을 선보일 수 있을 것이다.